{
 "title": "Pulp Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "prod : p,stage : s" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "logsource",
    "label": "logsource",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "System Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Pods Per App",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_info{container=~\"pulp-api|pulp-content|pulp-worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "pulp-${cluster:text}" },
     "label": "prod",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "pulp-${cluster:text}" },
     "label": "stage",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "[API] Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(pulp_api_request_duration_milliseconds_bucket[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(pulp_api_request_duration_milliseconds_bucket[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(pulp_api_request_duration_milliseconds_bucket[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "[Content] Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(pulp_content_request_duration_milliseconds_bucket[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(pulp_content_request_duration_milliseconds_bucket[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(pulp_content_request_duration_milliseconds_bucket[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Content Upload Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "filter @logStream like /pulp-${cluster:text}_pulp-api/ \n| filter message =~ /\\/api\\/pulp\\/.*?\\/api\\/v3\\/uploads\\/.*?\\//\n| parse message /\\('?pulp \\[(?<correlation_id>.*?)\\]: (?<host>.*?) - (?<remote_user>.*?) \\[(?<date>.*)\\] \"(?<method>.*?) \\/api\\/pulp\\/(?<domain>.*?)\\/api\\/v3\\/uploads\\/(?<uuid>.*?)\\/ (?<HttpVersion>.*?)\" (?<status_code>\\d+) (?<response_length>\\d+) (?<referrer>.*?) (?<user_agent>.*?)(',\\s)?(?<response_time>\\d+)?\\)/\n| filter method IN ['POST', 'PATCH', 'PUT']\n| stats pct(response_time, 99) by bin(5m)\n",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    },
    {
     "expression": "filter @logStream like /pulp-${cluster:text}_pulp-api/ \n| filter message =~ /\\/api\\/pulp\\/.*?\\/api\\/v3\\/uploads\\/.*?\\//\n| parse message /\\('?pulp \\[(?<correlation_id>.*?)\\]: (?<host>.*?) - (?<remote_user>.*?) \\[(?<date>.*)\\] \"(?<method>.*?) \\/api\\/pulp\\/(?<domain>.*?)\\/api\\/v3\\/uploads\\/(?<uuid>.*?)\\/ (?<HttpVersion>.*?)\" (?<status_code>\\d+) (?<response_length>\\d+) (?<referrer>.*?) (?<user_agent>.*?)(',\\s)?(?<response_time>\\d+)?\\)/\n| filter method IN ['POST', 'PATCH', 'PUT']\n| stats pct(response_time, 95) by bin(5m)\n",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    },
    {
     "expression": "filter @logStream like /pulp-${cluster:text}_pulp-api/ \n| filter message =~ /\\/api\\/pulp\\/.*?\\/api\\/v3\\/uploads\\/.*?\\//\n| parse message /\\('?pulp \\[(?<correlation_id>.*?)\\]: (?<host>.*?) - (?<remote_user>.*?) \\[(?<date>.*)\\] \"(?<method>.*?) \\/api\\/pulp\\/(?<domain>.*?)\\/api\\/v3\\/uploads\\/(?<uuid>.*?)\\/ (?<HttpVersion>.*?)\" (?<status_code>\\d+) (?<response_length>\\d+) (?<referrer>.*?) (?<user_agent>.*?)(',\\s)?(?<response_time>\\d+)?\\)/\n| filter method IN ['POST', 'PATCH', 'PUT']\n| stats pct(response_time, 90) by bin(5m)\n",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "[API] Request rate of [2xx, 3xx, 4xx, 5xx]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_status_code)(rate(pulp_api_request_duration_milliseconds_count{http_target!~\"api/pulp/api/v3/livez/|api/pulp/api/v3/status/\",http_status_code=\"2xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_status_code)(rate(pulp_api_request_duration_milliseconds_count{http_status_code=\"4xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_status_code)(rate(pulp_api_request_duration_milliseconds_count{http_status_code!~\"4xx|2xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[Content] Request rate of [2xx, 3xx, 4xx, 5xx]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 23 },
   "targets": [
    {
     "expr": "sum by (http_status_code)(rate(pulp_content_request_duration_milliseconds_count{http_status_code=\"2xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_status_code)(rate(pulp_content_request_duration_milliseconds_count{http_status_code=\"3xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_status_code)(rate(pulp_content_request_duration_milliseconds_count{http_status_code=\"4xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_status_code)(rate(pulp_content_request_duration_milliseconds_count{http_status_code=\"5xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Size of Served Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (domain_name) (rate(pulp_artifacts_size_counter_Bytes_total[$__rate_interval]) * $__interval_ms / 1000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage by Domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (domain_name) (pulp_space_usage_bytes))",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expression": "filter @logStream like /pulp-${cluster:text}_pulp-content/ |\nfilter message like /\\/api\\/pulp-content\\/.*?\\/.*?\\/.*? HTTP.*/ |\nparse message /(?<host>.*?) (?<date>\\[.*?\\]) \"(?<method>.*?) \\/api\\/pulp-content\\/(?<domain>.*?)\\/.*? (?<HttpVersion>.*?)\" \\d+ \\d+ \".*?\" \".*?\" \"(HIT|MISS)\" \"(?<ArtifactSize>\\d+)\"( \"(?<OrgId>.*?)\")?$/ |\nstats sum(ArtifactSize) as requested_artifact_size by domain,bin(5m)\n\n# limit defines the max number of events (in the below lines, at max 5 log messages will be queried)\n# since we cannot define a limit based on the number of different domains, doing a sort | limit would not be useful in this scenario and would just generate more load\n#|sort requested_artifact_size desc\n#|limit 5",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "domain",
      "bin(5m)"
     ]
    }
   ]
  },
  {
   "title": "Longest Unblocked Task Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(pulp_tasks_longest_unblocked_time_seconds)",
     "legendFormat": "task"
    }
   ]
  },
  {
   "title": "Unblocked Tasks Waiting in the Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 49 },
   "targets": [
    {
     "expr": "sum(pulp_tasks_unblocked_queue)",
     "legendFormat": "tasks"
    }
   ]
  },
  { "title": "Log Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Number of XML/RPM Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "fields @timestamp, @logStream, @message,  kubernetes.namespace_name | filter @logStream like /pulp-${cluster:text}_pulp-content/ | filter @message like \".rpm\" | stats count(*) as rpm by bin(5m)",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    },
    {
     "expression": "fields @timestamp, @logStream, @message,  kubernetes.namespace_name | filter @logStream like /pulp-${cluster:text}_pulp-content/ | filter @message like \".xml\" | stats count(*) as xml by bin(5m)",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Size of served XML/RPM Artifacts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "fields @timestamp, @logStream, @message,  kubernetes.namespace_name\n| filter @logStream like /pulp-${cluster:text}_pulp-content/\n| filter @message like \".rpm\"\n| parse @message 'HIT\\\" \\\"*\\\"' as rpm_size_hit\n| parse @message 'MISS\\\" \\\"*\\\"' as rpm_size_miss\n| stats sum(coalesce(rpm_size_hit, 0) + coalesce(rpm_size_miss, 0)) as rpm by bin(5m)",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    },
    {
     "expression": "fields @timestamp, @logStream, @message,  kubernetes.namespace_name\n| filter @logStream like /pulp-${cluster:text}_pulp-content/\n| filter @message like \".xml\"\n| parse @message 'HIT\\\" \\\"*\\\"' as xml_size_hit\n| parse @message 'MISS\\\" \\\"*\\\"' as xml_size_miss\n| stats sum(coalesce(xml_size_hit, 0) + coalesce(xml_size_miss, 0)) as xml by bin(5m)",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Successful Tasks and Failed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 65 },
   "targets": [
    {
     "expression": "fields @logStream, @message\n| filter @logStream like /pulp-${cluster:text}_pulp-(worker)/ \n| parse @message /Task\\[(?<task_name>[^\\]]+)\\]/\n| filter ispresent(task_name)\n| stats count() as failed_tasks by bin(1h)\n",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "bin(1h)" ]
    },
    {
     "expression": "fields @logStream, @message\n| filter @logStream like /pulp-${cluster:text}_pulp-(worker)/\n| filter @message like /Task completed/\n| stats count() as completed_tasks by bin(1h)\n",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "Successful tasks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @logStream, @message\n| filter @logStream like /pulp-${cluster:text}_pulp-(worker)/ \n| filter message like /Task completed/\n| stats count() as task_count",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pulp-worker non-immediate tasks by task type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @logStream, @message | filter @logStream like /pulp-${cluster:text}_pulp-(worker)/\n| filter message like /Starting task/\n| parse @message 'task_type: *,' as task_type\n| parse @message 'immediate: *,' as immediate\n| filter immediate=\"False\"\n| stats count(*) by task_type as task_type_count",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "task_type_count" ]
    }
   ]
  },
  {
   "title": "Pulp-Worker Immediate/Non Immediate Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 84 },
   "targets": [
    {
     "expression": "fields @logStream, @message,  kubernetes.namespace_name | filter @logStream like /pulp-${cluster:text}_pulp-(worker)/\n| filter message like /Starting task/\n| parse @message 'task_type: *,' as task_type\n| parse @message 'immediate: *,' as immediate\n| parse @message 'deferred: *\"' as deferred\n| filter immediate=\"True\"\n| stats count(*) as task_count by bin(1h), immediate",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [
      "bin(1h)",
      "immediate"
     ]
    },
    {
     "expression": "fields @logStream, @message,  kubernetes.namespace_name | filter @logStream like /pulp-${cluster:text}_pulp-(worker)/\n| filter message like /Starting task/\n| parse @message 'task_type: *,' as task_type\n| parse @message 'immediate: *,' as immediate\n| parse @message 'deferred: *\"' as deferred\n| filter immediate=\"False\"\n| stats count(*) as task_count by bin(1h), immediate",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [
      "bin(1h)",
      "immediate"
     ]
    }
   ]
  },
  {
   "title": "Tasks per type of worker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 94 },
   "targets": [
    {
     "expression": "fields @logStream, @message, kubernetes.labels.pod as pod | filter @logStream like /pulp-${cluster:text}_pulp-(api|content|worker)/\n| filter message like /Task completed/\n| stats count(*) by bin(1h), pod\n\n\n\n",
     "logGroups": [
      { "arn": "$logsource", "name": "$logsource" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [
      "bin(1h)",
      "pod"
     ]
    }
   ]
  },
  { "title": "Stakeholders resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "RHEL-AI repositories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "pulp_rhel_ai_repositories_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Content-Sources domains",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 105 },
   "targets": [
    {
     "expr": "pulp_content_sources_domains_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}