apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pulp
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pulp-otel-config
  data:
    otel-collector-config: |
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:10000
      processors:
        batch:
        memory_limiter:
          check_interval: 1s
          limit_mib: 768
        transform:
          error_mode: ignore
          metric_statements:
            - context: metric
              statements:
                - set(description, "Duration of HTTP server requests.") where name == "http.server.duration"
                - set(description, "Number of active HTTP server requests.") where name == "http.server.active_requests"
      exporters:
        prometheus:
          endpoint: "0.0.0.0:9000"
          namespace: pulp
          metric_expiration: 60m
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [transform, memory_limiter, batch]
            exporters: [prometheus]

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: pulp-otel-collector
  spec:
    envName: "${ENV_NAME}"
    testing:
      iqePlugin: content-sources
    deployments:
    - name: otel-collector
      replicas: 1
      webServices:
        private:
          enabled: true
      podSpec:
        image: "registry.redhat.io/rhosdt/opentelemetry-collector-rhel8"
        args:
         - "--config"
         - "file:/etc/otelcol-contrib/otel-collector-config.yaml"
        volumes:
          - name: otel-config
            configMap:
              name: pulp-otel-config
        volumeMounts:
          - name: otel-config
            mountPath: /etc/otelcol-contrib/otel-collector-config.yaml
            subPath: otel-collector-config
        resources:
          requests:
            cpu: ${{OTEL_COLLECTOR_CPU_REQUEST}}
            memory: ${{OTEL_COLLECTOR_MEMORY_REQUEST}}
          limits:
            cpu: ${{OTEL_COLLECTOR_CPU_LIMIT}}
            memory: ${{OTEL_COLLECTOR_MEMORY_LIMIT}}

parameters:
  - name: OTEL_COLLECTOR_CPU_REQUEST
    description: Amount of CPU to request for OpenTelemetry Collector container
    value: "250m"
  - name: OTEL_COLLECTOR_CPU_LIMIT
    description: Limit of CPU use by OpenTelemetry Collector container
    value: "500m"
  - name: OTEL_COLLECTOR_MEMORY_REQUEST
    description: Amount of memory to request for OpenTelemetry Collector container
    value: "1024Mi"
  - name: OTEL_COLLECTOR_MEMORY_LIMIT
    description: Limit of memory use by OpenTelemetry Collector container
    value: "2048Mi"
