"""Tests for the admin content-cache flush endpoint.

The endpoint flushes the content app's Redis cache for all distributions while
preserving worker and task locks that live in the same Redis instance.
"""

import time
import uuid
from urllib.parse import urljoin

import pytest
import requests
from django.conf import settings

# The content-cache flush exercises Redis. Redis is only guaranteed to be
# reachable when the content cache is enabled OR a Redis worker is in use
# (mirrors pulpcore.app.redis_connection._redis_is_needed). Skip only when
# neither holds, so the test still runs under WORKER_TYPE=pulpcore as long as
# CACHE_ENABLED is True.
pytestmark = pytest.mark.skipif(
    not settings.CACHE_ENABLED and settings.WORKER_TYPE != "redis",
    reason="Requires Redis (CACHE_ENABLED or WORKER_TYPE=redis)",
)

FLUSH_URL_PATH = "/api/pulp/debug/flush-content-cache/"

# Redis keys that stand in for worker/task locks. These match the namespaces the
# RedisWorker uses (pulpcore/tasking/redis_locks.py) and MUST survive a flush.
SENTINEL_LOCK_KEYS = {
    "pulp:resource_lock:cache-flush-sentinel": "sentinel-owner",
    "task:cache-flush-sentinel": "sentinel-owner",
}


@pytest.fixture
def flush_url(bindings_cfg):
    return urljoin(bindings_cfg.host, FLUSH_URL_PATH)


@pytest.fixture
def admin_auth(bindings_cfg):
    return (bindings_cfg.username, bindings_cfg.password)


@pytest.fixture
def redis_conn():
    """A real Redis connection to the same instance the content app and workers use.

    Obtained via the content Cache (pulpcore.cache) so the test relies only on the
    plugin-facing cache API rather than pulpcore internals.
    """
    from pulpcore.cache import Cache

    conn = Cache().redis
    if conn is None:
        pytest.skip("Redis connection not available")
    return conn


@pytest.fixture
def cache_key_for():
    """Build the content-cache hash key for a distribution's base_path."""
    from django.conf import settings

    def _key(base_path, domain_name="default"):
        if settings.DOMAIN_ENABLED:
            return f"{domain_name}:{base_path}"
        return base_path

    return _key


@pytest.fixture
def distributed_file_content(file_bindings, gen_object_with_cleanup, monitor_task):
    """Sync a file repo, publish it, and distribute it.

    Returns the distribution object (its base_url serves cacheable content).
    """
    remote = gen_object_with_cleanup(
        file_bindings.RemotesFileApi,
        {
            "name": f"cache-flush-remote-{uuid.uuid4()}",
            "url": "https://fixtures.pulpproject.org/file/PULP_MANIFEST",
            "policy": "immediate",
        },
    )
    repo = gen_object_with_cleanup(
        file_bindings.RepositoriesFileApi,
        {"name": f"cache-flush-repo-{uuid.uuid4()}", "remote": remote.pulp_href},
    )
    monitor_task(file_bindings.RepositoriesFileApi.sync(repo.pulp_href, {}).task)
    repo = file_bindings.RepositoriesFileApi.read(repo.pulp_href)
    publish_task = monitor_task(
        file_bindings.PublicationsFileApi.create({"repository_version": repo.latest_version_href}).task
    )
    publication_href = publish_task.created_resources[0]
    distribution = gen_object_with_cleanup(
        file_bindings.DistributionsFileApi,
        {
            "name": f"cache-flush-dist-{uuid.uuid4()}",
            "base_path": f"cache-flush-{uuid.uuid4()}",
            "publication": publication_href,
        },
    )
    return distribution


def _populate_cache(distribution, redis_conn, cache_hash_key):
    """GET the distribution's directory listing through the content app until its
    cache hash appears. The listing is generated by the content app (no artifact
    streaming), so it populates the cache without depending on the storage backend's
    object-serving mode.
    """
    content_url = distribution.base_url
    if not content_url.endswith("/"):
        content_url += "/"

    for _ in range(10):
        resp = requests.get(content_url, timeout=60)
        resp.raise_for_status()
        if redis_conn.exists(cache_hash_key):
            return
        time.sleep(0.5)
    pytest.fail(f"Content cache hash {cache_hash_key!r} was never populated after serving content")


def test_flush_distribution_cache_preserves_locks(
    flush_url, admin_auth, redis_conn, cache_key_for, distributed_file_content, monitor_task
):
    """Flushing clears distribution cache hashes but leaves worker/task lock keys intact."""
    distribution = distributed_file_content
    cache_hash_key = cache_key_for(distribution.base_path)

    # Seed sentinel lock keys that represent worker/task locks sharing this Redis.
    for key, value in SENTINEL_LOCK_KEYS.items():
        redis_conn.set(key, value)

    try:
        # Populate the content cache for the distribution through normal serving.
        _populate_cache(distribution, redis_conn, cache_hash_key)

        # Preconditions: the content cache hash exists and the lock keys exist.
        assert redis_conn.exists(cache_hash_key), "content cache should be populated before flush"
        for key in SENTINEL_LOCK_KEYS:
            assert redis_conn.exists(key), f"lock key {key} should exist before flush"

        # Flush the content cache — the endpoint dispatches a task; wait for it.
        response = requests.post(flush_url, auth=admin_auth, timeout=60)
        assert response.status_code == 202, response.text
        task = monitor_task(response.json()["task"])
        assert task.result["distributions"] >= 1
        assert task.result["cache_keys_deleted"] >= 1

        # The distribution's content cache hash is gone...
        assert not redis_conn.exists(cache_hash_key), "content cache should be flushed"
        # ...but the worker/task lock keys survive.
        for key in SENTINEL_LOCK_KEYS:
            assert redis_conn.exists(key), f"lock key {key} must be preserved by the flush"
    finally:
        redis_conn.delete(*SENTINEL_LOCK_KEYS.keys())


def test_flush_requires_admin(flush_url):
    """Unauthenticated requests are rejected."""
    response = requests.post(flush_url, timeout=60)
    assert response.status_code in (401, 403), response.text
