# Generated by Django 4.2.10 on 2024-08-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0120_get_url_removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.domain')),
            ],
            options={
                'unique_together': {('org_id', 'domain')},
            },
        ),
    ]
