# Generated by Django 4.2.10 on 2024-08-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domainorg',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='domainorg',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domainorg',
            name='org_id',
            field=models.CharField(db_index=True, null=True),
        ),
    ]
