# Generated by Django 4.2.10 on 2024-09-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_domainorg_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainorg',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.domain'),
        ),
    ]
