# Generated by Django 4.2.20 on 2025-03-18 09:59

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_upstreampulp_policy'),
        ('service', '0006_vulnerabilityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleLogReport',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('log_url', models.URLField(max_length=2000)),
                ('errors', models.JSONField()),
                ('error_count', models.IntegerField()),
                ('role_filter', models.JSONField(default=list)),
                ('domain', models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]