# Generated by Django 4.2.20 on 2025-03-17 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_vulnerabilityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleLogReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('log_url', models.URLField(max_length=2000)),
                ('errors', models.JSONField()),
                ('error_count', models.IntegerField()),
                ('role_filter', models.JSONField(default=list)),
            ],
        ),
    ]