# Generated by Django 4.2.10 on 2025-06-02 18:32

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_distribution_checkpoint_publication_checkpoint'),
        ('service', '0007_alter_vulnerabilityreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorg',
            name='domains',
            field=models.ManyToManyField(related_name='domains', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='domainorg',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='core.domain'),
        ),
    ]
