# Generated by Django 4.2.10 on 2025-06-02 18:41

from django.db import migrations
from pulp_service.app.models import DomainOrg


def copy_domain_to_domains(apps, schema_editor):
    DomainOrg = apps.get_model('service', 'DomainOrg')
    through_model = DomainOrg.domains.through
    to_create = []
    for obj in DomainOrg.objects.all():
        if obj.domain:
            to_create.append(
                through_model(
                    domainorg_id=obj.pk,
                    domain_id=obj.domain_id
                )
            )
    if to_create:
        through_model.objects.bulk_create(to_create, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_domainorg_domains_alter_domainorg_domain'),
    ]

    operations = [
        migrations.RunPython(copy_domain_to_domains),
    ]
