# Generated by Django 4.2.19 on 2025-06-06 15:09

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_distribution_checkpoint_publication_checkpoint'),
        ('service', '0009_copy_domain_to_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainorg',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_org', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='domainorg',
            name='domains',
            field=models.ManyToManyField(related_name='domain_orgs', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityreport',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
