# Generated by Django 4.2.10 on 2025-06-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_distribution_checkpoint_publication_checkpoint'),
        ('service', '0010_alter_domainorg_domain_alter_domainorg_domains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainorg',
            name='domain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_org', to='core.domain'),
        ),
    ]
