# Generated by Django 4.2.10 on 2025-06-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_domainorg_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainorg',
            name='domain',
        ),
    ]
