# Generated by Django 4.2.24 on 2025-09-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_task_app_lock'),
        ('service', '0012_remove_domainorg_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorg',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.group'),
        ),
    ]
