# Generated by Django 4.2.24 on 2025-09-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0012_remove_domainorg_domain'),
        ('core', '0139_task_app_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorg',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domainorgs', to='core.group'),
        ),
        migrations.AlterField(
            model_name='domainorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
