# Generated by Django 4.2.24 on 2025-09-15 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0144_delete_old_appstatus'),
        ('service', '0012_remove_domainorg_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorg',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_orgs', to='core.group'),
        ),
        migrations.AlterField(
            model_name='domainorg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
