# Generated by Django 5.2.12 on 2026-03-31 18:12

import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_artifact_artifact_domain_size_index'),
        ('service', '0014_yankedpackagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yankedpackagereport',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AgentScanReport',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('reports', models.TextField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('pulp_domain', models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
                ('repo_versions', models.ManyToManyField(blank=True, to='core.repositoryversion')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
