# Generated by Django 5.2.12 on 2026-06-18 18:18

import django.db.models.deletion
import pulpcore.app.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_upstreampulp_connect_timeout_and_more'),
        ('service', '0016_pypiyanksmonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypiyankmonitor',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pypiyankmonitor',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repository'),
        ),
        migrations.AlterField(
            model_name='pypiyankmonitor',
            name='repository_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repositoryversion'),
        ),
        migrations.DeleteModel(
            name='AgentScanReport',
        ),
    ]
